# Generated by Django 3.1.3 on 2020-11-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=30)),
                ('uwagi', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Sieci VLAN',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('nazwa_hosta', models.CharField(max_length=50)),
                ('numer_vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.vlan')),
            ],
            options={
                'verbose_name_plural': 'Hosty',
            },
        ),
    ]
