# Generated by Django 3.1.3 on 2020-11-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='uwagi',
            field=models.TextField(default=''),
        ),
    ]
