# Generated by Django 3.1.3 on 2020-11-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20201125_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='uwagi',
            field=models.TextField(default='Brak'),
        ),
    ]
